entero num1,num2,tabla,inicial,fina,x
inicio
	escriba "ingresa el numero inicial de la tabla"
	lea inicial
	llamar nueva_linea
	escriba"ingresa el numero final de la tabla"
	lea fina
	llamar nueva_linea
	para num1<-inicial hasta fina haga 
		escriba " tabla del: ", num1
		para x<-1 hasta 5 haga
			num2<-num1*x
			escriba num1," por ",x," igual a: ",num2
			llamar nueva_linea
		fin para
	fin para		
fin